// <auto-generated />
using System;
using CodaxyProject.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodaxyProject.Migrations
{
    [DbContext(typeof(CodaxyDBContext))]
    partial class CodaxyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodaxyProject.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "Dejan Bunic",
                            Status = 0,
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 806, DateTimeKind.Local).AddTicks(4655),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 809, DateTimeKind.Local).AddTicks(6114)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "Pero Peric",
                            Status = 2,
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 809, DateTimeKind.Local).AddTicks(6861),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 809, DateTimeKind.Local).AddTicks(6885)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "Pero Budak",
                            Status = 1,
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 809, DateTimeKind.Local).AddTicks(6901),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 809, DateTimeKind.Local).AddTicks(6905)
                        });
                });

            modelBuilder.Entity("CodaxyProject.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            CreatedBy = "Dejan Bunic",
                            Description = "hibridni kukuruz",
                            Name = "kukuruz",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 810, DateTimeKind.Local).AddTicks(9825),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(215)
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            CreatedBy = "Dejan Bunic",
                            Description = "crveni",
                            Name = "krompir",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1020),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1042)
                        },
                        new
                        {
                            Id = 3,
                            CartId = 2,
                            CreatedBy = "Pero Peric",
                            Description = "crveni",
                            Name = "krompir",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1075),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1079)
                        },
                        new
                        {
                            Id = 4,
                            CartId = 2,
                            CreatedBy = "Pero Peric",
                            Description = "ljuta paprika",
                            Name = "cips",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1083),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1086)
                        },
                        new
                        {
                            Id = 5,
                            CartId = 3,
                            CreatedBy = "Pero Budak",
                            Description = "slane przene",
                            Name = "sjemenke bundeve",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1147),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1151)
                        },
                        new
                        {
                            Id = 6,
                            CartId = 3,
                            CreatedBy = "Pero Budak",
                            Description = "zaledjeni fileti",
                            Name = "oslic",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1156),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1159)
                        },
                        new
                        {
                            Id = 7,
                            CartId = 3,
                            CreatedBy = "Pero Budak",
                            Description = "sa ljesnjakom",
                            Name = "cokolada",
                            TimeCreated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1163),
                            TimeUpdated = new DateTime(2021, 10, 11, 18, 31, 56, 811, DateTimeKind.Local).AddTicks(1166)
                        });
                });

            modelBuilder.Entity("CodaxyProject.Models.CartItem", b =>
                {
                    b.HasOne("CodaxyProject.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodaxyProject.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
